spring.application.name=sneaker-drops-2

spring.datasource.url=jdbc:mysql://localhost:3306/sneakerdrops
spring.datasource.username=root
spring.datasource.password=5hrnWNhF

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update